### ISSUE TITLE
Define the size of the embedded video

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/noembedMedia#2]
When embedding video with this plugin, the width / height seem not to be define consistently. Is it a problem from noembed or from the plugin?

An interesting feature would be to allow to choose a size for the embedded item.

**Comment by franck-paul** [comment]
Je viens de regarder ce que retourne l'API sur cette URL : `https://www.youtube.com/embed/0H4rq0L9OSw`

Le code HTML :

```html
<iframe width=" 200" height="113" src="https://www.youtube.com/embed/0H4rq0L9OSw?feature=oembed" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
```

Si je vais directement sur Youtube et que j'utilise la fonction de partage (intégration), voilà le code fourni :

```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/0H4rq0L9OSw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

J'en conclus que ce que retourne noembed.com est un peu moisi !

**Comment by franck-paul** [comment]
Le dépôt Github de l'outil : [https://github.com/leedo/noembed](https://github.com/leedo/noembed)

Ça vaudrait peut-être le coup d'ouvrir un ticket là-bas…

**Comment by franck-tomek** [comment]
Merci d'avoir regardé, je vais faire ça.

**Comment by franck-paul** [comment]
[Le ticket](https://github.com/leedo/noembed/issues/122), histoire de garder un lien et d'éventuellement surveiller si quelque chose est fait…
