### ISSUE TITLE
Probleme d'insertion video avec Dotclear 2.26

### ISSUE THREAD

**Issue by Draven73** [franck-paul/noembedMedia#3]
Bonjour
voici mon souci. Depuis la mise à jour récente de Dotclear, je suis en version 2.26, je ne peux plus insérer de vidéo dans les billets. L'icône "média extérieur" ne fonctionne plus. Le fenêtre s'ouvre bien lorsque je clique dessus, je copie/colle le lien à insérer mais en cliquant sur "Insérer" rien ne se passe. Je dois les insérer manuellement pour l'instant, un peu rébarbatif.
Merci de votre aide pour résoudre ce problème. Pour info je suis en Php8 et tourne sur OVH.

**Comment by franck-paul** [comment]
Une nouvelle version va bientôt (quelques jours) être publiée, je propose d'attendre jusque là pour vérifier si le bug persiste.

En attendant la console du navigateur fournit une erreur ou rien ?

**Comment by franck-paul** [comment]
Publiée ce matin, à mettre à jour et à tester pour voir si quelque chose a bougé.

**Comment by Draven73** [comment]
Le navigateur ne fournit aucune erreur. Il ne se passe simplement rien quand je clique sur Insérer. Rien d'autre.

OK. Je testerais après la MAJ. On verra si le bug persiste.
Merci

**Comment by Draven73** [comment]
La MAJ a été faite et ca fonctionne à nouveau parfaitement. Merci pour votre aide :)
